### ISSUE TITLE
worksheet 07

### ISSUE THREAD

**Issue by conan-sw** [data-8/su24#32]
Worksheet Number: 07
Worksheet Link: https://drive.google.com/file/d/1aIlqVwBc0p1dJ8V-zbQwDl5jWDgUBacc/view?usp=sharing

**Comment by jonathanferrari** [comment]
Updated `_config.yml` for worksheet 07 link:
- Worksheet: [Lab 07 Worksheet](https://drive.google.com/file/d/1aIlqVwBc0p1dJ8V-zbQwDl5jWDgUBacc/view?usp=sharing)
